### ISSUE TITLE
error on start downloading curse

### ISSUE THREAD

**Issue by jlopezjuy** [riazXrazor/udemy-dl#10]
Hello, i have this error when im trying to download one curse from udemy

Logging in, please wait...          /usr/lib/node_modules/udemy-dl/lib/core.js:50
      cb(r,b.match(/name='csrfmiddlewaretoken'\s+value='(.*)'/)[1]);
                                                               ^

TypeError: Cannot read property '1' of null
    at Request._callback (/usr/lib/node_modules/udemy-dl/lib/core.js:50:64)
    at Request.self.callback (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

**Comment by Aniruddh-J** [comment]
I have made a fix for this and created a pull request on this repo. 

In the meantime, you can use the fixed version I have here: https://github.com/Aniruddh-J/udemy-dl

**Comment by riazXrazor** [comment]
tnx bro, hv merged it n released the fixed version.
