### ISSUE TITLE
Issue while downloading 

### ISSUE THREAD

**Issue by shahsatish** [riazXrazor/udemy-dl#13]
@riazXrazor ,
This is the error i get.

Logging in, please wait...          /usr/local/lib/node_modules/udemy-dl/lib/core.js:50
      cb(r,b.match(/name='csrfmiddlewaretoken'\s+value='(.*)'/)[1]);
                                                               ^

TypeError: Cannot read property '1' of null
    at Request._callback (/usr/local/lib/node_modules/udemy-dl/lib/core.js:50:64)
    at Request.self.callback (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

Thanks
Satish

**Comment by riazXrazor** [comment]
Plz update this issue has been fixed

**Comment by shahsatish** [comment]
@riazXrazor ,
How do i update the package?

**Comment by riazXrazor** [comment]
Jst uninstall n install the package again.
