### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by VikasRana** [riazXrazor/udemy-dl#16]
C:\Users\Administrator\AppData\Roaming\npm\node_modules\udemy-dl\lib\core.js:308
      var course_data_len = course_data['results'].length;
                                                   ^

TypeError: Cannot read property 'length' of undefined
    at Request._callback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\udemy-dl\lib\core.js:308:52)
    at Request.self.callback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

**Comment by riazXrazor** [comment]
can you please install the updated version and try again

**Comment by ghost** [comment]
I'm getting the same error

> C:\Users\USER\AppData\Roaming\npm\node_modules\udemy-dl\lib\core.js:356
>       var course_data_len = course_data['results'].length;
>                                                    ^
> 
> TypeError: Cannot read property 'length' of undefined
>     at Request._callback (C:\Users\eDot 3\AppData\Roaming\npm\node_modules\udemy-dl\lib\core.js:356:52)
>     at Request.self.callback (C:\Users\eDot 3\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:186:22)
>     at emitTwo (events.js:126:13)
>     at Request.emit (events.js:214:7)
>     at Request.<anonymous> (C:\Users\eDot 3\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:1163:10)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at IncomingMessage.<anonymous> (C:\Users\eDot 3\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:1085:12)
>     at Object.onceWrapper (events.js:313:30)
>     at emitNone (events.js:111:20)

>

**Comment by akshay3001** [comment]
getting the same err
