### ISSUE TITLE
Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by oscar-dario-pabon** [riazXrazor/udemy-dl#27]
As the title says:

![image](https://user-images.githubusercontent.com/6578465/39327255-227de5f8-495d-11e8-8b07-5d9ef19de820.png)
/usr/local/lib/node_modules/udemy-dl/node_modules/cheerio/lib/parse.js:55
    var oldParent = node.parent || node.root,
                         ^

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/usr/local/lib/node_modules/udemy-dl/node_modules/cheerio/lib/parse.js:55:26)
    at module.exports (/usr/local/lib/node_modules/udemy-dl/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (/usr/local/lib/node_modules/udemy-dl/node_modules/cheerio/lib/static.js:22:14)
    at Request._callback (/usr/local/lib/node_modules/udemy-dl/lib/core.js:198:31)
    at Request.self.callback (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
![image](https://user-images.githubusercontent.com/6578465/39327354-6bf29d32-495d-11e8-9ce7-1429f2a81173.png)

**Comment by htkcodes** [comment]
same here

**Comment by RonyRizk** [comment]
same here

**Comment by sirStephen** [comment]
same here

**Comment by riazXrazor** [comment]
May be udemy code has changed i'll look into it.

**Comment by sirStephen** [comment]
Try accessing their site earlier on today and they having issues. They said they working on it. Maybe that's what is causing the issue

**Comment by riazXrazor** [comment]
yup i visited the site, it seems slugish, and they some portions has been worked on, so my code also has to be updated accordingly.

**Comment by RonyRizk** [comment]
any update ?

**Comment by JC-JackClark** [comment]
FYI I have a fix for this, but I need to readd the functionality to pick resolution.

Will make a pull request shortly
