### ISSUE TITLE
Error when downloading on latest version

### ISSUE THREAD

**Issue by davidhenley** [riazXrazor/udemy-dl#32]
```
◝ Logging in, please wait...          /Users/david/.config/yarn/global/node_modules/udemy-dl/lib/core.js:53
      cb(r,b.match(/name='csrfmiddlewaretoken'\s+value='(.*)'/)[1]);
                                                               ^

TypeError: Cannot read property '1' of null
    at Request._callback (/Users/david/.config/yarn/global/node_modules/udemy-dl/lib/core.js:53:64)
    at Request.self.callback (/Users/david/.config/yarn/global/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/david/.config/yarn/global/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/david/.config/yarn/global/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by riazXrazor** [comment]
What is ur OS ?

**Comment by davidhenley** [comment]
Mac High Sierra

**Comment by davidhenley** [comment]
Mac

*David Henley*
615-438-3334

**Comment by riazXrazor** [comment]
hmm its only occuring in the mac i think, not sure why. i only hv a linux and windows, ok i'll hv a deeper look.

**Comment by riazXrazor** [comment]
i hv updated the code which is causing issue, and released a new version, can you check if its fixed.

**Comment by davidhenley** [comment]
That worked! Thanks.
