### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by IbrahimJakmour** [riazXrazor/udemy-dl#33]
◜ Checking course url...                   /usr/lib/node_modules/udemy-dl/lib/core.js:115
        callback(b.match(/data-course-id="(\d+)"/)[1]);
                                                  ^

TypeError: Cannot read property '1' of null
    at Request._callback (/usr/lib/node_modules/udemy-dl/lib/core.js:115:51)
    at Request.self.callback (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)

you have a problem with udl please fix

**Comment by riazXrazor** [comment]
it just occured once, is it reoccuring, and
what is ur OS ?

**Comment by IbrahimJakmour** [comment]
my os is arch linux antergos ,,i used udl before on windows not yrs another it work fine and download all files and videos then it was outdated , so on my arch i used npm install udemy-dl one month ago it work fine and all was good except it download only videos and skips the files . if u enter the commend udl -u blabla -p balabla url  it gives error ,, so i must enter -u then enter -p then it gives me list of all my courses ,,i like when i write 1 command and i wish it can download every thing 
and btw its a great tool thank u
