### ISSUE TITLE
Error occurred during download

### ISSUE THREAD

**Issue by Proinfinto** [riazXrazor/udemy-dl#45]
There was an error in the downloading phase and now it continually gives this error?

```
C:\Users\User_PC\AppData\Roaming\npm\node_modules\udemy-dl\lib\core.js:97
        callback(b.match(/data-course-id="(\d+)"/)[1]);
                                                  ^
TypeError: Cannot read property '1' of null
    at Request._callback (C:\Users\User_PC\AppData\Roaming\npm\node_modules\udemy-dl\lib\core.js:97:51)
    at Request.self.callback (C:\Users\User_PC\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (C:\Users\User_PC\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (C:\Users\User_PC\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

**Comment by riazXrazor** [comment]
@Proinfinto thanks for the feedback, will be looking into it soon.

**Comment by riazXrazor** [comment]
Hi, try not including the course url and selecting the course after login, it should fix ur issue.
