### ISSUE TITLE
Cannot read property 'split'

### ISSUE THREAD

**Issue by Melgan** [riazXrazor/udemy-dl#65]
On my computer with udemy-dl 1.0, where it works fine there is issue.I install on vm ubuntu 18.4 than debian v 2.0 and everywhere same issue:

? Enter your password: ******
? Select a course to download: 1 ) Docker Mastery: with Kubernetes +Swarm from a Docker Captain
? Select the maximum video resolution to download: 720
  ◞ Initializing, please wait...          /usr/local/lib/node_modules/udemy-dl/lib/core.js:619
                    var file = query_obj.filename.split('.');
                                                  ^

TypeError: Cannot read property 'split' of undefined
    at Request._callback (/usr/local/lib/node_modules/udemy-dl/lib/core.js:619:51)
    at Request.self.callback (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

**Comment by johndoe1969** [comment]
Enter your password: ********************
https://www.udemy.com/join/login-popup/
Fetching courses... done
? Select a course to download: 1) Spanish for Beginners. The Complete Method. Level 1
? Select the maximum video resolution to download: Auto
initializing... done
/usr/lib/node_modules/udemy-dl/src/lib/core.js:387
          var file = query_obj.filename.split(".");
                                        ^

TypeError: Cannot read property 'split' of undefined
    at Request._callback (/usr/lib/node_modules/udemy-dl/src/lib/core.js:387:41)
    at Request.self.callback (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by riazXrazor** [comment]
try the new release it should fix this
