### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by johndoe1969** [riazXrazor/udemy-dl#67]
I get this when I choose "AUTO" as the download resolution. I get the "split" error when I choose 720p as resolution (see issue #65). I'm running version 2.0.5 of udemy-dl on Ubuntu 18.04.

Fetching courses... done
? Select a course to download: 1) Spanish for Beginners. The Complete Method. Level 1
? Select the maximum video resolution to download: 720
starting download... done

Chapter : 1 - Introduction
Video :  1 - Introduction and guidelines for following the course.x-mpegURL
Resolution :  Autop
Location : /home/john/Downloads/udemy-dl-master/1 - Introduction/1 - Introduction and guidelines for following the course.x-mpegURL
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Invalid URI "/assets/9323852/files/1325716/9323852/2017-08-19_19-46-12-f1749bc934ff3a6d1ea475c2095a18ee/aa0077c4e2243466a206d07f63cfd02b363d.m3u8"
    at Request.init (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:273:31)
    at new Request (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:127:8)
    at request (/usr/lib/node_modules/udemy-dl/node_modules/request/index.js:53:10)
    at /usr/lib/node_modules/udemy-dl/src/lib/core.js:507:22
    at xfs.mkdir.er (/usr/lib/node_modules/udemy-dl/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
Emitted 'error' event at:
    at Request.init (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:273:17)
    at new Request (/usr/lib/node_modules/udemy-dl/node_modules/request/request.js:127:8)
    [... lines matching original stack trace ...]
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

**Comment by riazXrazor** [comment]
udemy has changed video format i guess to for some course.x-mpegURL :(
