### ISSUE TITLE
Says this to me can you help me?

### ISSUE THREAD

**Issue by ghost** [riazXrazor/udemy-dl#8]
_                                          _   _
  _   _    __| |   ___   _ __ ___    _   _            __| | | |
 | | | |  / _` |  / _ \ | '_ ` _ \  | | | |  _____   / _` | | |
 | |_| | | (_| | |  __/ | | | | | | | |_| | |_____| | (_| | | |
  \__,_|  \__,_|  \___| |_| |_| |_|  \__, |          \__,_| |_|
                                     |___/
? Enter your Udemy username : Myname@hotmail.com
? Enter your password: password
? Enter the course url to download from udemy: https://www.udemy.com/beavoiceactor/
C:\Users\Myname\AppData\Roaming\npm\node_modules\udemy-dl\lib\core.js:308
      var course_data_len = course_data['results'].length;
                                                   ^

TypeError: Cannot read property 'length' of undefined
    at Request._callback (C:\Users\Myname\AppData\Roaming\npm\node_modules\udemy-dl\lib\core.js:308:52)
    at Request.self.callback (C:\Users\Myname\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Users\Myname\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Users\Myname\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:312:30)
    at emitNone (events.js:110:20)

C:\Users\Myname>

this :  ^ under "l" (length)

**Comment by riazXrazor** [comment]
Hi crybf,

Thanks for the feedback.
Does the error occur for any course url or jst this one ?

**Comment by ghost** [comment]
any course url

**Comment by shahsatish** [comment]
Hi,
This happened to me as well, but only for few of the courses, one of which is "devops-and-continuous-integration-with-jenkins-pipelines". Do we have any resolution so far? Any help would be greatly appreciated.

**Comment by riazXrazor** [comment]
some of the issues has been fixed.

**Comment by vjmtrailheadx** [comment]
Hi, 
This happened for me as well. But for some courses only

**Comment by riazXrazor** [comment]
Ok, I'll test few of the courses to find out the cause if i can and then
try to fix it.

**Comment by shahsatish** [comment]
@riazXrazor,
This seems to be happening when the courses are not enrolled for. I enrolled in these courses and was able to download it successfully, you may want to add a warning message here. However I'm getting a new error now. will post that in a new thread, will you please look into that as well.
